### ISSUE TITLE
Błąd serwera 500 - brak klucza głównego w 'SaleAdviceDocumentElement'

### ISSUE THREAD

**Issue by witmus** [troncomputers/optimaapi#10]
Dzień dobry,

po ostatniej aktualizacji API w odpowiedzi na każde żądanie (z wyłączeniem danych z bazy konfiguracyjnej) zwraca poniższy wyjątek.

![image](https://github.com/troncomputers/optimaapi/assets/43937361/a49ba15c-035b-455b-aeca-69be9bceebe5)

**Comment by troncomputers** [comment]
Nie powinno takim błędem rzucić, ponieważ w przypadku tego modelu nic się nie zmieniło. Został tylko przeniesiony głębiej. W przypadku dodawania dokumentu ProForma wszystko zostało tak jak było w poprzedniej wersji. Zmieniło się tylko przekazywanie więcej niż jednej zaliczki. Czy ten błąd występują podczas dodawania dokumentu?

**Comment by troncomputers** [comment]
Proszę spróbować nową wersję z chmury

**Comment by witmus** [comment]
Błąd uległ zmianie.

```
  "message": "Unable to determine the relationship represented by navigation 'SaleDocument.AdviceElements' of type 'ICollection<SaleAdviceDocumentElement>'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.",
  "code": "EXCEPTION",
  "additionalMessage": ""
```

![image](https://github.com/troncomputers/optimaapi/assets/43937361/5dd36bca-681c-4598-8aa6-20d6489371a8)

**Comment by troncomputers** [comment]
Wrzuciłem update. Wychodzi na to, że wcześniejszy model nie był odzwierciedleniem tego co jest w bazie dlatego takich konfiguracji nie musiałem robić. Model `SaleDocument` jest tabelą `TraNag` w Optimie i dodanie do niego listy elementów zaliczki spowodowało konflikt. Myślę, że teraz będzie działać.

**Comment by witmus** [comment]
Niestety, SqlClient pozostaje niepocieszony.

![image](https://github.com/troncomputers/optimaapi/assets/43937361/94e6f047-3589-4271-ba95-44792f8d1b09)

**Comment by troncomputers** [comment]
Mogę prosić o JSON jaki jest przekazywany do API

**Comment by witmus** [comment]
[proforma_multiple_advice.txt](https://github.com/troncomputers/optimaapi/files/12585604/proforma_multiple_advice.txt)

**Comment by troncomputers** [comment]
Update na chmurze. Proszę o weryfikację

**Comment by witmus** [comment]
Proforma z jedną zaliczką dodała się prawidłowo, od dwóch w górę niestety leci timeout.

![image](https://github.com/troncomputers/optimaapi/assets/43937361/2f5fa73a-384f-49b2-9130-1c6cd71f635e)

**Comment by troncomputers** [comment]
Update na chmurze. Proszę przetestować.

**Comment by witmus** [comment]
Działa, dziękuję bardzo.
