### ISSUE TITLE
OptimaAPI Handel - dodawanie faktur zaliczkowych do proform już znajdujących się w bazie Optimy

### ISSUE THREAD

**Issue by witmus** [troncomputers/optimaapi#11]
Dzień dobry,

w poprzedniej aktualizacji endpoint POST `api/documents` został rozszerzony o załączanie listy zaliczek do dodawanej faktury proforma. Niestety ten sam endpoint nie pozwala na "dosyłanie" faktur zaliczkowych do znajdującej się już w optimie faktury proforma. Czy istniałaby możliwość modyfikacji istniejącego lub dodanie nowego endpointa który pozwoliłby na takie dodawanie zaliczek?

**Comment by troncomputers** [comment]
Ale to nie uległo zmianie. Jest jakiś błąd?

**Comment by witmus** [comment]
Rzeczywiście sprawdziłem i ta opcja działa jeżeli w ciele żądania przekazujemy zaliczkę w polu `SaleDocument` którego polu `zwrId` przypisujemy Id proformy (do tej pory Id proformy umieszczałem w polu `relId`, stąd moje skonfundowanie). Dodana w ten sposób zaliczka zostaje powiązana z proformą, natomiast w odróżnieniu od zaliczek dodawanych razem z proformą posiada ona typ `KOR` zamiast `FS`. Czy mógłbym w takim razie jedynie prosić o korektę tego typu tj. żeby wszystkie zaliczki konsekwentnie miały typ `FS`?

![image](https://github.com/troncomputers/optimaapi/assets/43937361/4d6fa1df-5e11-40cc-bfaa-7cbcc8efa992)

**Comment by witmus** [comment]
Nieaktualne, temat ujęty w watku #17
