### ISSUE TITLE
Błąd przy generowaniu zdarzeń kasowo-bankowych dla dodawanego dokumentu rejestru VAT

### ISSUE THREAD

**Issue by witmus** [troncomputers/optimaapi#12]
Dzień dobry,

dodanie dokumentu rejestru VAT przy użyciu EP POST `api/vatdocuments` prawidłowo tworzy dokument wraz z pozycjami. Niestety, żądanie zawsze zwraca błąd z kodem statusu 500 o następującej treści:

```
{
  "message": "An error occurred while saving the entity changes. See the inner exception for details.",
  "code": "EXCEPTION",
  "additionalMessage": "##OPT32025##%1%=TraNag##\r\nThe transaction ended in the trigger. The batch has been aborted."
}
```
Dzięki logom API udało mi się namierzyć ten trigger i ustalić, iż w ramach próby dodania do dokumentu zdarzeń bankowych wykonuje on sprawdzenie przewidziane dla dokumentu handlowego, zamiast znajdującego się tuż pod nim sprawdzenia dla rejestru VAT.
![image](https://github.com/troncomputers/optimaapi/assets/43937361/d17d2586-9eaa-4df0-a9b6-8ace330de33a)

Czy mógłbym prosić o sprawdzenie i poprawienie błędu?
Pozdrawiam

**Comment by troncomputers** [comment]
Przekazałem informacje na temat tego błędu Romanowi. Będzie się kontaktował w celach weryfikacyjnych.

**Po krótce:**
Wszelkiego rodzaju triggery są tworzone i wywoływane po stronie Optimy. To nie są nasze triggery. W swaggerze przy tym polu `BZd_DokumentTyp`, w api `BankEvent.DocumentType` jest opis jakie wartości do czego przyjmuje. Domyślnie ma `1`
