### ISSUE TITLE
Błędna wartość zwracana przy edycji

### ISSUE THREAD

**Issue by witmus** [troncomputers/optimaapi#2]
Niektóre endpointy PUT zamiast wartości boolowskiej zwracają jej wartość zrzutowaną na typ całkowitoliczbowy (np. 1 zamiast TRUE).
Dotyczy to endpointów:
* `/api/categories`
* `/api/vatdocuments`
* `/api/vatdocuments/vatelements`
* `/api/vatdocuments/vat7elements`

**Comment by troncomputers** [comment]
Poprawione
