### ISSUE TITLE
Brak możliwości pobrania pliku przypisanego do faktury

### ISSUE THREAD

**Issue by witmus** [troncomputers/optimaapi#4]
Wartość pola `file` przy pobieraniu rejestru VAT zawsze wynosi `NULL`.

Uwaga: działanie tej funkcjonalności było sprawdzane wyłącznie na fakturach, do których załącznik został dodany za pośrednictwem Państwa API (w samej Optimie załącznik wyświetla się prawidłowo)

**Comment by troncomputers** [comment]
Konsultowałem kwestię z szefostwem i z tego co wiem to ustalone było, że mamy dać możliwość **tylko** wrzucenia załącznika do dokumentu. Ja nie wiem nic na temat pobierania załącznika.

**Comment by witmus** [comment]
Teraz sobie przypominam, że faktycznie takie ustalenia były, przepraszam za zamieszanie.
