### ISSUE TITLE
Generowanie identyfikatora księgowego dla rejestru VAT

### ISSUE THREAD

**Issue by witmus** [troncomputers/optimaapi#5]
W poprzedniej wersji API do dodawanego rejestru VAT identyfikator księgowy generował się automatycznie. W aktualnej wersji API wymaga zawarcia identyfikatora w ciele żądania POST `/api/vatdocuments`. Czy istniałaby możliwość przywrócenia tej funkcjonalności?

**Comment by troncomputers** [comment]
Z jakiegoś powodu dopisałem do tego pola atrybut `[Required]` mimo, iż pole jest `Nullable`. Poprawione.

PS.
Aktualna paczka na chmurze. Link ten sam.
