### ISSUE TITLE
Błąd przy pobraniu rejestru VAT z pozycją bez kategorii

### ISSUE THREAD

**Issue by witmus** [troncomputers/optimaapi#6]
Przy pobieraniu rejestru VAT przez EP `/api/vatdocuments/{id}`  lub jego pozycji przez EP `/api/vatdocuments/vatelements/{id}`, jeżeli którakolwiek z pozycji nie ma przypisanej kategorii (`categoryId` = `NULL`) rzucany jest wyjątek jak poniżej. Czy byłaby możliwość przywrócenia rozwiązania z poprzedniej wersji, tj. żeby w przypadku braku kategorii pole `categoryId` przyjmowało domyślną wartość `0`?

![image](https://user-images.githubusercontent.com/43937361/195558190-91a88ba0-aef4-4be4-84b8-aef8dcedbbb4.png)

![image](https://user-images.githubusercontent.com/43937361/195558912-974f050a-1c43-4e8a-a692-a0739f55984e.png)

**Comment by troncomputers** [comment]
EP `/api/vatdocuments/{id}` pobiera też pozycje dokumentu, a to na pozycji dokumentu nie było `nullable` w `CategoryId`. 

PS.
Problemów z `nullable` może być więcej. Po przejściu na EF Core walidacja modeli jest troszkę inna, a baza danych Optimy nie pomaga w projektowaniu klas.

Aktualna paczka na chmurze.
