### ISSUE TITLE
Literówka w modelu nagłówka ewidencji VAT w EnovaAPI

### ISSUE THREAD

**Issue by witmus** [troncomputers/optimaapi#7]
Po aktualizacji EnovaAPI z 10.11 zamiast pola `bruttoSymbol` występuje pole `ruttoSymbol`. W efekcie zwracany jest błąd niezależnie od danych wejściowych

![image](https://user-images.githubusercontent.com/43937361/201133760-ed107ffe-3ae1-423d-a9be-93abac071619.png)

![image](https://user-images.githubusercontent.com/43937361/201134259-3f78e4af-846a-47ef-aea9-448a2b6ed9c7.png)

PS. Czy ewentualne kolejne uwagi/pytania dotyczące EnovaAPI zamieszczać również tutaj? Zasugerowałem się obecnością odnośnika w nagłówku swaggera

**Comment by troncomputers** [comment]
Poprawione. Nowy zip na chmurze. Do czasu jak nie wyjdzie oficjalna wersja proszę o pisanie błędów na maila do mnie z DW do Romana.
