### ISSUE TITLE
OptimaAPI handel - brak kwot w fakturze zaliczkowej

### ISSUE THREAD

**Issue by witmus** [troncomputers/optimaapi#8]
Dodawanie samej faktury pro forma przebiega prawidłowo, natomiast w przypadku dodawanej wraz z nią faktury zaliczkowej nie przenoszą się kwoty (załącznik). W efekcie API próbuje wygenerować dla faktury zaliczkowej płatność o zerowej kwocie co jest niemożliwe przez ograniczenia w bazie Optimy (pro forma i zaliczka w załączniku dodały się gdyż ograniczenia te zostały przeze mnie tymczasowo zdjęte). Dodatkowo załączam zawartość żądania dodania pro formy z załącznika. Prosiłbym o informację czy żądanie jest w jakiś sposób błędne lub niekompletne, czy też jest to błąd API.

![proforma_zaliczka](https://github.com/troncomputers/optimaapi/assets/43937361/93527029-51e9-49ae-94ac-221e658f9558)

[proforma.txt](https://github.com/troncomputers/optimaapi/files/11574541/proforma.txt)

**Comment by troncomputers** [comment]
Przepraszam za spóźnienie, ale masa rzeczy na głowie i umknęło. Ogarniam ✌️

**Comment by troncomputers** [comment]
Moim zdaniem to jest jakiś wyjątkowy przypadek, albo nie potrafię go u siebie powtórzyć. 

Fakt, faktem, jest ten json troszkę dziwny, ponieważ wystawiamy proformę na jedną pozycję, a pozycje faktury zaliczkowej są 3
```json
  "saleAdviceElements": [
    {
      "productId": 1,
      "amount": 120
    },
{
      "productId": 2,
      "amount": 121
    },
{
      "productId": 3,
      "amount": 122
    }
  ]
```

Szczerze mówiąc minęło już trochę czasu jak zaglądałem ostatni raz do tego kodu. Z tego co widzę, to po dodaniu ProFormy, pobieramy elementy tej proformy i w pętli na podstawie tych elementów pobieramy elementy zaliczki. W tym przypadku `"productId": 53,`, a elementy zaliczki nie mają żadnej pozycji z `"productId": 53,`, stąd może się brać `0` w płatnościach, ponieważ to jest liczone na podstawie elementów proformy i zaliczki.

Ja zmieniłem u siebie na swoje produkty, dla proformy ustawiłem `"productId": 1,` oraz zostawiłem tak jak jest w `saleAdviceElements` i jak widać na screenie poniżej zrobił płatność na 121 zł, ponieważ tylko jeden element spełniał warunek istnienia na proformie i na zaliczce, który ma wartość 121 zł.

Nie wiem czy dobrze to tłumaczę i ciężko mi też na szybko ustalić dlaczego taka logika została zastosowana. Wydaje mi się, że nie możemy zaliczkować na towar, którego nie ma na proformie, stąd taki typ "walidacji".

W przypadku gdy `adviceElement is null` - nie ma towaru z zaliczki na proformie to mam w kodzie `continue`

```csharp
var adviceElement = document.SaleAdviceElements.FirstOrDefault(x => x.ProductId == element.ProductId); // element = pozycja proformy
if (adviceElement is null)
    continue;
```

![proforma_zaliczka](https://github.com/troncomputers/optimaapi/assets/29543667/219bc0c1-2964-4145-b39a-dc4be73c66aa)

**Comment by witmus** [comment]
Ok wszystko jasne. Sprawdziłem teraz u siebie i po poprawnym przypisaniu `productId` kwoty prawidłowo się przenoszą. Bardzo dziękuję za pomoc.
